version: "3.3"
services:
  gazebo:
    build:
      context: ./examples/gazebo
    volumes:
      - ./examples/common/sshd_config:/etc/ssh/sshd_config
      - ./examples/common/env-loader.sh:/home/husarion/env-loader.sh
    environment:
      - DISPLAY
  ros:
    build:
      context: ./examples/rosbot
      args:
        ARCH: ${ARCH}
    volumes:
      - ./examples/common/sshd_config:/etc/ssh/sshd_config
      - ./examples/common/env-loader.sh:/home/husarion/env-loader.sh
  app:
    env_file: .env
    build:
      context: ./
      args:
        ARCH: ${ARCH}
    ports:
      - "8000:8000"
